apiVersion: v1
metadata:
  name: kube-lego
  namespace: nginx-ingress
data:
  # modify this to specify your address
  lego.email: "INSERT YOUR EMAIL HERE"
  # configure letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
